[Variables]
SKINLIST=Combilaunch | Plainext | MIUI-Shade | ModularClocks | ModularPlayers | Keystrokes | Keylaunch | ValliStart | QuickNote | IdleStyle

Combilaunch=1.3
Plainext=1.81
MIUI-Shade=2.01
ModularClocks=2.11
ModularPlayers=1.31
Keystrokes=1.31
Keylaunch=1.5
ValliStart=2.96
QuickNote=1.31
IdleStyle=1.4
ModularVisualizer=0.0
MuzeFlyout=0.0
GestureLaunch=0.0

BETASKINS=ModularVisualizer
DOWNSKINS=Keystrokes
