[Variables]
SKINLIST=Combilaunch | Plainext | MIUI-Shade | ModularClocks | ModularPlayers | Keystrokes | Keylaunch | ValliStart | QuickNote | IdleStyle | ModularVisualizer

Combilaunch=1.3
Plainext=1.81
MIUI-Shade=2.03
ModularClocks=2.2
ModularPlayers=2.41
Keystrokes=1.5
Keylaunch=2.01
ValliStart=3.0
QuickNote=1.4
IdleStyle=1.42
ModularVisualizer=1.04
YourFlyouts=0.0
YourMixer=1.4

NewsID=30
Page2ID=2
Page3ID=0
