[Variables]
UserNameCheckVariable=Jax Tam 
LastVersionNumber=00036
; ----------------------------- Scaling variables ---------------------------- ;
; Set.S=0.9
Set.P=(40*[Set.S])
Set.Home.P=(100*[Set.S])
Set.R=(10)
; Set.W=(1200*[Set.S])
; Set.H=(740*[Set.S])
Set.L=(200*([Set.S]+0.2))
; --------------------------- Appearance variables --------------------------- ;
Set.Pri_Color=12,12,12
Set.Sec_Color=28,28,28
Set.Ter_Color=35,35,35
Set.Accent_Color=255, 117, 81
Set.Text_Color=242,240,255
Set.SubText_Color=120,120,120
Sec.SaveLocation=#SKINSPATH##Skin.Name#\@Resources\Vars.inc
; ------------------------ Background check variables ------------------------ ;
Set.Auto_Refresh=1
Set.BackgroundCheckTime=30
Core.Master=3
; ------------------------------ DeviantArtLinks ----------------------------- ;
Combilaunch.L=881177085
Plainext.L=881628513
ModularClocks.L=883898019
MIUI-Shade.L=885183361
ModularPlayers.L=886577256
Keystrokes.L=889349339
Keylaunch.L=890749449

[Set.S]
Measure=Calc
Formula=0.8
