[Variables]
UserNameCheckVariable=Jax Tam
; ----------------------------- Scaling variables ---------------------------- ;
; Set.S=0.9
Set.P=(40*[Set.S])
Set.R=(20)
; Set.W=(1200*[Set.S])
; Set.H=(740*[Set.S])
Set.L=(200*[Set.S])
; --------------------------- Appearance variables --------------------------- ;
Set.Pri_Color=12,12,12
Set.Sec_Color=28,28,28
Set.Ter_Color=30, 30, 30
Set.Accent_Color=37, 171, 117
Set.Text_Color=242,240,255
Set.SubText_Color=120,120,120
Sec.SaveLocation=#SKINSPATH##Skin.Name#\@Resources\Vars.inc
; ------------------------ Background check variables ------------------------ ;
Set.Auto_Refresh=1
Set.Background_Check_MS=3600000

[Set.S]
Measure=Calc
Formula=0.84933333333333
