[Variables]
UserNameCheckVariable=Jax Tam
LastVersionNumber=00032
; ----------------------------- Scaling variables ---------------------------- ;
; Set.S=0.9
Set.P=(40*[Set.S])
Set.Home.P=(100*[Set.S])
Set.R=(10)
; Set.W=(1200*[Set.S])
; Set.H=(740*[Set.S])
Set.L=(200*([Set.S]+0.2))
; --------------------------- Appearance variables --------------------------- ;
Set.Pri_Color=12,12,12
Set.Sec_Color=28,28,28
Set.Ter_Color=35,35,35
Set.Accent_Color=255, 117, 81
Set.Text_Color=242,240,255
Set.SubText_Color=120,120,120
Sec.SaveLocation=#SKINSPATH##Skin.Name#\@Resources\Vars.inc
; ------------------------ Background check variables ------------------------ ;
Set.Auto_Refresh=1
Set.BackgroundCheckTime=1
Core.Master=3

[Set.S]
Measure=Calc
Formula=1
