
[Q1]
Meter=String
Text=The animation seems to be lagging?
MeterStyle=Set.String:S | Sec.Q:S
[A1]
Meter=String
Text=If you are on a low-end device, the slide-down animation might not be smooth for you. Turning animation off can help with performance
MeterStyle=Set.String:S | Sec.A:S
[Set.Div:S10101]
Meter=Shape
MeterStyle=Set.Div:S

[Q2]
Meter=String
Text=Spotify music player doesn't work properly?
MeterStyle=Set.String:S | Sec.Q:S
[A2]
Meter=String
Text=You'll have to install spicetify-cli and the webnowplaying plugin for it in order for the skin to fetch album art and status
MeterStyle=Set.String:S | Sec.A:S
[Set.Div:S10102]
Meter=Shape
MeterStyle=Set.Div:S

[Q3]
Meter=String
Text=How do I unload the shade properly?
MeterStyle=Set.String:S | Sec.Q:S
[A3]
Meter=String
Text=Do so with the right-click context menu instead of the manage panel
MeterStyle=Set.String:S | Sec.A:S
[Set.Div:S10103]
Meter=Shape
MeterStyle=Set.Div:S

[Q4]
Meter=String
Text=How can I hide certain notifications?
MeterStyle=Set.String:S | Sec.Q:S
[A4]
Meter=String
Text=You can hide them with a toggle at their corresponding section inside the settings panel
MeterStyle=Set.String:S | Sec.A:S
[Set.Div:S10104]
Meter=Shape
MeterStyle=Set.Div:S

[Q5]
Meter=String
Text=Why does the hotkey not work? 
MeterStyle=Set.String:S | Sec.Q:S
[A5]
Meter=String
Text=If you've changed the keys yourself, make sure they are following the right formatting. Additionally if you are using keyhook, some key pressing orders might not work.
MeterStyle=Set.String:S | Sec.A:S
[Set.Div:S10105]
Meter=Shape
MeterStyle=Set.Div:S

[Q6]
Meter=String
Text=What do override and doesn't override mean?
MeterStyle=Set.String:S | Sec.Q:S
[A6]
Meter=String
Text=Override means that the keys would block the default functions of such hotkey, doesn't override would not block the functions but rather work side-by-side with it
MeterStyle=Set.String:S | Sec.A:S
[Set.Div:S10106]
Meter=Shape
MeterStyle=Set.Div:S

[Q7]
Meter=String
Text=
MeterStyle=Set.String:S | Sec.Q:S
[A7]
Meter=String
Text=
MeterStyle=Set.String:S | Sec.A:S
[Set.Div:S10107]
Meter=Shape
MeterStyle=Set.Div:S

[Q8]
Meter=String
Text=
MeterStyle=Set.String:S | Sec.Q:S
[A8]
Meter=String
Text=
MeterStyle=Set.String:S | Sec.A:S
[Set.Div:S10108]
Meter=Shape
MeterStyle=Set.Div:S

[Q9]
Meter=String
Text=
MeterStyle=Set.String:S | Sec.Q:S
[A9]
Meter=String
Text=
MeterStyle=Set.String:S | Sec.A:S
[Set.Div:S10109]
Meter=Shape
MeterStyle=Set.Div:S

[Q10]
Meter=String
Text=
MeterStyle=Set.String:S | Sec.Q:S
[A10]
Meter=String
Text=
MeterStyle=Set.String:S | Sec.A:S
[Set.Div:S101010]
Meter=Shape
MeterStyle=Set.Div:S