[12]
Meter=String
Text=Fill color
X=r
Y=(#Sec.P#)R
MeterStyle=Sec.String:S


; ---------------------------------------------------------------------------- ;
;                                     Input                                    ;
; ---------------------------------------------------------------------------- ;

[1st]
Meter=Shape
MeterStyle=Set.ColorPacity:S
Y=[12:Y]
[Value21]
Meter=String
Text=#1stOpacity#
MeterStyle=Sec.String:S | Set.Pacity:S