[Variables]
@includeSkin=#@#SecVar.inc
;Retrives the skin name
@includeSkinVars=#SKINSPATH##Skin.Name#\@Resources\Vars.inc
@includeSkinVer=#SKINSPATH##Skin.Name#\@Resources\Version.inc
;get current skin data
Skin.Appearance=Plainext | ModularClocks | MIUIShade | ModularPlayers | WatchOS | Keystrokes | Keylaunch | ValliStart
Skin.Layout=Keystrokes | Keylaunch
; Skin.General=Combilaunch | Plainext | ModularClocks | MIUIShade | ModularPlayers
Skin.Media=MIUIShade | ModularPlayers | ValliStart
Skin.Render=ModularClocks
Skin.FAQ=MIUIShade | ModularClocks | ModularPlayers