[ModularClocks]
Meter=Image
X=r
Y=([RecommendedSkins:H]*([Set.S]-1)+10*[Set.S])R
ImageName=#@#Images\Cards\ModularClocks.png
MeterStyle=SkinIcon:S
[ModularClocksDes]
Meter=String
MeterStyle=Set.String:S | SkinText:S
Text=ModularClocks#CRLF# Modern, clock, minimal
[Plainext]
Meter=Image
ImageName=#@#Images\Cards\Plainext.png
MeterStyle=SkinIcon:S
[PlainextDes]
Meter=String
MeterStyle=Set.String:S | SkinText:S
Text=Plainext#CRLF# System, Retro
[ModularPlayers]
Meter=Image
ImageName=#@#Images\Cards\ModularPlayers.png
MeterStyle=SkinIcon:S
[ModularPlayersDes]
Meter=String
MeterStyle=Set.String:S | SkinText:S
Text=ModularPlayers#CRLF# Modern, Music, Minimal
