[IdleStyle]
Meter=Image
X=r
Y=([RecommendedSkins:H]*([Set.S]-1)+10*[Set.S])R
ImageName=#@#Images\Cards\IdleStyle.png
MeterStyle=SkinIcon:S
[IdleStyleDes]
Meter=String
MeterStyle=Set.String:S | SkinText:S
Text=IdleStyle#CRLF# Screensavers reimagined.
[ValliStart]
Meter=Image
ImageName=#@#Images\Cards\ValliStart.png
MeterStyle=SkinIcon:S
[ValliStartDes]
Meter=String
MeterStyle=Set.String:S | SkinText:S
Text=ValliStart#CRLF# Start menu replacement
[Keylaunch]
Meter=Image
ImageName=#@#Images\Cards\Keylaunch.png
MeterStyle=SkinIcon:S
[KeylaunchDes]
Meter=String
MeterStyle=Set.String:S | SkinText:S
Text=Keylaunch#CRLF# Animated hotkey launcher
[QuickNote]
Meter=Image
X=(#Set.P#)
Y=(10*[Set.S])R
ImageName=#@#Images\Cards\QuickNote.png
MeterStyle=SkinIcon:S
[QuickNoteDes]
Meter=String
MeterStyle=Set.String:S | SkinText:S
Text=QuickNote#CRLF# Quick access notepad
[MIUI-Shade]
Meter=Image
ImageName=#@#Images\Cards\MIUI-Shade.png
MeterStyle=SkinIcon:S
[MIUI-ShadeDes]
Meter=String
MeterStyle=Set.String:S | SkinText:S
Text=MIUI-Shade#CRLF# Animated control center
[Keystrokes]
Meter=Image
ImageName=#@#Images\Cards\Keystrokes.png
MeterStyle=SkinIcon:S
[KeystrokesDes]
Meter=String
MeterStyle=Set.String:S | SkinText:S
Text=Keystrokes#CRLF# Overlay, Gaming, Hotkey
