[Variables]
CCW=1085
CCH=778
SkinX=463
SkinY=186
[Position]
Meter=Shape
MeterStyle=CtxBox:S | Position:Act
[PositionIcon]
Meter=Image
MeterStyle=CtxIcon:S
[PositionText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Position:Text
[Unload]
Meter=Shape
MeterStyle=CtxBox:S | Unload:Act
[UnloadIcon]
Meter=Image
MeterStyle=CtxIcon:S
[UnloadText]
Meter=String
MeterStyle=Ctx.String:S | CtxText:S | Unload:Text
