[Header2]
Meter=String
X=([ContentContainer:W]/2)
Y=(60*[Set.S])
ClipString=2
W=([ContentContainer:W]/2)
DynamicVariables=1
StringAlign=Center
Text=Although you can customize settings for Combilaunch in the core, it does not provide 100% compatiblitiy. For combilaunch, Core only serves as an update changer, hence using the classic settings menu for combilaunch customization is highly recommended. To open the classic settings menu, right click combilaunch and click Config.
FontSize=(10*[Set.S])
FontCOlor=150,150,150
MeterStyle=Set.String:S